version: 2.1
jobs:
  build:
    docker:
      - image: monacoremo/nix:2020-01-31-62bbc2ab-circleci
    steps:
      - checkout
      - run:
          name: Pre-load Nix environment for the basic application
          command: nix-shell --run "echo Loaded basic Nix environment"
      - run:
          name: Set up the test result directory structure
          command: mkdir -p test-results/{basic,basic-repeat,fullstack,fullstack-repeat}
      - run:
          name: Grant access to the non-root test user
          command: |
            # There must be a better way to do this...
            chown -R user:user /root/project
            chmod o+xr /root /root/project
      - run:
          name: Run tests for the basic application
          command: |
            nix-shell --run \
              'su-exec user:user ./deploy/test-local.sh --junitxml=test-results/basic/junit.xml'
      - run:
          name: Re-run basic tests to make sure that they are idempotent
          command: |
            nix-shell --run \
              'su-exec user:user ./deploy/test-local.sh --junitxml=test-results/basic-repeat/junit.xml'
      - store_test_results:
            path: test-results
